name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pa-i-movie" #Must be unique in Heroku
          heroku_email: "wilson.weng@oocl.com"

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test
